version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - echo "install"
  build:
    commands:
      - echo "build"
  post_build:
    commands:
      - echo "post build"
