version: 0.2


env:
  variables:
    TERRAFORM_VERSION: 0.10.3
    TERRAFORM_SHA256: f316c6ff8b2abe257250d19cbe0e3cf745dedfa67b37bb4afaf95e0291efeade

phases:
  install:
    commands:
      - echo "********** debug **********"
      - echo "TERRAFORM_VERSION=${TERRAFORM_VERSION}"
      - echo "TERRAFORM_SHA256=${TERRAFORM_SHA256}"
      - echo "GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}"
      - echo "AWS_ACCESS_KEY=${AWS_ACCESS_KEY}"
      - echo "AWS_SECRET_KEY=${AWS_SECRET_KEY}"
      - echo "AWS_REGION=${AWS_REGION}"
      - echo "PUBLIC_KEY=${PUBLIC_KEY}"
      - echo "VPC_ID=${VPC_ID}"
      - echo 'aws_access_key = '\""${AWS_ACCESS_KEY}"\" >> terraform.auto.tfvars;
      - echo 'aws_secret_key = '\""${AWS_SECRET_KEY}"\" >> terraform.auto.tfvars;
      - echo 'aws_region = '\""${AWS_REGION}"\" >> terraform.auto.tfvars;
      - echo 'public_key = '\""${PUBLIC_KEY}"\" >> terraform.auto.tfvars;
      - echo 'vpc_id = '\""${VPC_ID}"\" >> terraform.auto.tfvars;
      - cat terraform.auto.tfvars
      - pwd
      - ls -larth
      - echo "********** install **********"
      - curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip 
      - echo "${TERRAFORM_SHA256} /tmp/terraform.zip" | sha256sum -c --quiet 
      - ls -larth /tmp/terraform*
      - unzip /tmp/terraform.zip -d /usr/bin/
      - ls -larth /usr/bin/terraform*
      - terraform init -no-color -input=false                          # init terraform
      - terraform plan -no-color -out=tfplan -input=false              # plan terraform
      - pwd
      - ls -larth
  build:
    commands:
      - echo "********** build **********"
      - terraform apply -no-color -parallelism=16 -input=false tfplan  # apply terraform
  post_build:
    commands:
      - echo "********** post build **********"
      - echo "********** done **********"
